### ISSUE TITLE
no directory for figure to go into in Figure 2 code

### ISSUE THREAD

**Issue by Swanson-Hysell** [bcych/TROUT#2]
There is not a directory `Figures` within the repo which results in an error for the code:

```
plt.savefig('Figures/forward_model_examples.pdf')
```

of

```
FileNotFoundError: [Errno 2] No such file or directory: 'Figures[/forward_model_examples.pdf]
```

It makes sense to either have the code create that directory or to have it there to start with.

**Comment by bcych** [comment]
Fixed in latest commit. Thanks for the report.
